### ISSUE TITLE
undefined method `callcc' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by chip** [pry/pry-exception_explorer#18]
Hi,

I just installed the `plymouth` gem and upon running my failing spec, I'm getting this exception:

```
/Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-exception_explorer-0.1.9/lib/pry-exception_explorer/core_ext.rb:91:in `raise': undefined method `callcc' for main:Object (NoMethodError)
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:240:in `rescue in load_dependency'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:233:in `load_dependency'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/webmock-1.8.0/lib/webmock.rb:3:in `<top (required)>'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
        from /Users/chip/code/woboinc/rentwb/config/application.rb:10:in `<top (required)>'
        from /Users/chip/code/woboinc/rentwb/config/environment.rb:4:in `require'
        from /Users/chip/code/woboinc/rentwb/config/environment.rb:4:in `<top (required)>'
        from /Users/chip/code/woboinc/rentwb/spec/spec_helper.rb:6:in `require'
        from /Users/chip/code/woboinc/rentwb/spec/spec_helper.rb:6:in `<top (required)>'
        from /Users/chip/code/woboinc/rentwb/spec/lib/skyo/order/discount_spec.rb:1:in `require'
        from /Users/chip/code/woboinc/rentwb/spec/lib/skyo/order/discount_spec.rb:1:in `<top (required)>'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
        from /Users/chip/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'

shell returned 1
```

Any clues on what the issue is?  Thanks in advance for any suggestions.

**Comment by banister** [comment]
Hi, plymouth has been replaced by [pry-rescue](https://github.com/ConradIrwin/pry-rescue)

**Comment by chip** [comment]
Sounds good.  Thank you!
